blank_issues_enabled: false
contact_links:
  - name: Community Support & Questions (Discord)
    url: https://discord.gg/knkNRYyQcm
    about: Join the Discord if you have questions or want to discuss AutoBOT with the community.