name: Auto Release

on:
    push:
        branches: [main, dev, better-cd]

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm'

            - run: npm ci

            - name: Build
              run: npm run build:all

            - name: Validate build outputs
              run: |
                  for file in dist/auto-image.{standalone,userscript,bookmarklet}.js dist/auto-image.bookmarklet.txt; do
                      test -s "$file" || (echo "Missing or empty: $file" && exit 1)
                  done
                  echo "✅ All outputs validated"

            - name: Generate version tag
              id: version
              run: |
                  VERSION="v$(date -u +%Y.%m.%d-%H%M%S)"
                  echo "tag=$VERSION" >> $GITHUB_OUTPUT
                  echo "Generated version: $VERSION"

            - name: Create Release
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  gh release create ${{ steps.version.outputs.tag }} \
                      --title "Auto Release ${{ steps.version.outputs.tag }}" \
                      --notes "Automated release from ${{ github.ref_name }} branch

                  Commit: ${{ github.sha }}

                  **Stable Direct URLs (raw files):**
                  - https://github.com/Staninna/WPlace-AutoBOT/releases/latest/download/auto-image.standalone.js
                  - https://github.com/Staninna/WPlace-AutoBOT/releases/latest/download/auto-image.userscript.js
                  - https://github.com/Staninna/WPlace-AutoBOT/releases/latest/download/auto-image.bookmarklet.js
                  - https://github.com/Staninna/WPlace-AutoBOT/releases/latest/download/auto-image.bookmarklet.txt

                  **Files included:**
                  - \`auto-image.standalone.js\` - Standalone version
                  - \`auto-image.userscript.js\` - Userscript version
                  - \`auto-image.bookmarklet.js\` - Bookmarklet JavaScript
                  - \`auto-image.bookmarklet.txt\` - Bookmarklet text" \
                      dist/auto-image.standalone.js \
                      dist/auto-image.userscript.js \
                      dist/auto-image.bookmarklet.js \
                      dist/auto-image.bookmarklet.txt